import LCD as _lcd
import Imaging as imaging
import Analysis as analysis

import warnings
import matplotlib.cbook
warnings.filterwarnings("ignore",category=matplotlib.cbook.mplDeprecation)

if __name__ == '__main__':

    
    #    1. SET UP

    #Set up Camera
    cam = imaging.Camera()
    cam.configureGPIO()
    cam.configureProperties()
    
    #Setup LCD
    lcd = _lcd.Lcd()
    lcd.boxMode()
    

    #    2. IMAGING

    #Begin the Imaging Sequence
    #Normalize Exposure and Spatial values

    images = imaging.Imaging(cam, "Patient 441")


   
    #This method is for running and plotting trials
    #images.runTrials() 
     
    raw_images = images.acquireImages()
    
    #Creates image plots
    analysis.Analysis(raw_images).imagePlots()
    
    #print("Image {} \n\n\n".format(images.acquireImages()))
    
    image_masks = images.normalizeSpatial()
    print("Image Masks {} \n\n\n".format(image_masks))

    #Apply mask generated by normalization
    masked_image = images.maskImage(image_masks)
    
    #Set to True for keeping plot on display
    analysis.Analysis(masked_image).imagePlots(True) 
    print("Masked Image {} \n\n\n".format(masked_image))


    #    3. Analysis

    #Calculate stats and plot
    stats = analysis.Analysis(masked_image)
    stats.findMax()
    stats.calcStats()   
    #stats.generatePlots()


    #    4. Cleanup
    
    cam.cleanUp()
    
        
